			function c1(id)
			{
				document.getElementById('t1').style.display="";	
				document.getElementById('t2').style.display="none";	
				document.getElementById('t3').style.display="none";	
				document.getElementById('t4').style.display="none";	
				document.getElementById('t5').style.display="none";
				document.getElementById('l1').style.background="#bfc2ba";	
				document.getElementById('l1').style.color="#10326b";	
				document.getElementById('l2').style.color="#fff";	
				document.getElementById('l3').style.color="#fff";	
				document.getElementById('l4').style.color="#fff";	
				document.getElementById('l5').style.color="#fff";	
				document.getElementById('l2').style.background="#10326b";	
				document.getElementById('l3').style.background="#10326b";	
				document.getElementById('l4').style.background="#10326b";	
				document.getElementById('l5').style.background="#10326b";	
			}
			function c2(id)
			{
				document.getElementById('t1').style.display="none";	
				document.getElementById('t2').style.display="";	
				document.getElementById('t3').style.display="none";	
				document.getElementById('t4').style.display="none";	
				document.getElementById('t5').style.display="none";
				document.getElementById('l1').style.background="#10326b";	
				document.getElementById('l2').style.background="#bfc2ba";
				document.getElementById('l2').style.color="#041c36";
				document.getElementById('l1').style.color="#fff";	
				document.getElementById('l3').style.color="#fff";	
				document.getElementById('l4').style.color="#fff";	
				document.getElementById('l5').style.color="#fff";	
				document.getElementById('l3').style.background="#10326b";	
				document.getElementById('l4').style.background="#10326b";	
				document.getElementById('l5').style.background="#10326b";	
			}
			function c3(id)
			{
				document.getElementById('t1').style.display="none";	
				document.getElementById('t2').style.display="none";	
				document.getElementById('t3').style.display="";	
				document.getElementById('t4').style.display="none";	
				document.getElementById('t5').style.display="none";	
				document.getElementById('l1').style.background="#10326b";	
				document.getElementById('l2').style.background="#10326b";	
				document.getElementById('l3').style.background="#bfc2ba";
				document.getElementById('l3').style.color="#10326b";	
				document.getElementById('l1').style.color="#fff";	
				document.getElementById('l2').style.color="#fff";	
				document.getElementById('l4').style.color="#fff";	
				document.getElementById('l5').style.color="#fff";	
				document.getElementById('l4').style.background="#10326b";	
				document.getElementById('l5').style.background="#10326b";	
			}
			function c4(id)
			{
				document.getElementById('t1').style.display="none";	
				document.getElementById('t2').style.display="none";	
				document.getElementById('t3').style.display="none";	
				document.getElementById('t4').style.display="";	
				document.getElementById('t5').style.display="none";
				document.getElementById('l1').style.background="#10326b";	
				document.getElementById('l2').style.background="#10326b";	
				document.getElementById('l3').style.background="#10326b";	
				document.getElementById('l4').style.background="#bfc2ba";
				document.getElementById('l4').style.color="#10326b";	
				document.getElementById('l3').style.color="#fff";	
				document.getElementById('l2').style.color="#fff";	
				document.getElementById('l1').style.color="#fff";	
				document.getElementById('l5').style.color="#fff";	
				document.getElementById('l5').style.background="#10326b";	
			}
			function c5(id)
			{
				document.getElementById('t1').style.display="none";	
				document.getElementById('t2').style.display="none";	
				document.getElementById('t3').style.display="none";	
				document.getElementById('t4').style.display="none";	
				document.getElementById('t5').style.display="";
				document.getElementById('l1').style.background="#10326b";	
				document.getElementById('l2').style.background="#10326b";	
				document.getElementById('l3').style.background="#10326b";	
				document.getElementById('l4').style.background="#10326b";	
				document.getElementById('l5').style.background="#bfc2ba";	
				document.getElementById('l5').style.color="#10326b";	
				document.getElementById('l4').style.color="#fff";	
				document.getElementById('l3').style.color="#fff";	
				document.getElementById('l2').style.color="#fff";	
				document.getElementById('l1').style.color="#fff";	
			}
